### ISSUE TITLE
To je prázdné :(

### ISSUE THREAD

**Issue by frantisekmachek** [s1vek/WA#1]
Co děěěěěěělaš ten repozitář je práázdný

**Comment by s1vek** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus nisi ex, fermentum ut sapien in, viverra dapibus turpis. Cras bibendum magna ex. Quisque pharetra dui in sem rutrum vehicula. Suspendisse potenti. Nunc cursus dolor et sapien molestie, ac tempor augue cursus. Integer feugiat efficitur ipsum, malesuada ultrices ex porttitor sit amet. Vivamus consectetur accumsan nunc at semper. In vehicula vestibulum nisl nec pharetra. Morbi vehicula nibh et ante feugiat, vitae hendrerit lacus vehicula.

**Comment by Teriffy** [comment]
Já tento problém nepovažuji za uzavřený.
